# Generated by Django 4.1.6 on 2023-02-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Technology', models.CharField(max_length=150)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
